# Generated by Django 2.2 on 2019-09-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('number_in_stock', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('liked', models.BooleanField(default=False)),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generes.Geners')),
            ],
        ),
    ]
